import Head from 'next/head';
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FitnessAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/resources/faviconnnnnn.ico" />
        {/* Add any other head elements here */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
